Code-Book/urls.py
"""
URL configuration for the project.

This file defines the URL patterns for the project, mapping URLs to corresponding views.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),

    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
""" URL configuration for the 'api' app """

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'profiles', views.ProfileViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'auth', views.AuthViewSet, basename='auth')

urlpatterns = [
    path('', include(router.urls)),
    path('reviews/', views.ReviewAPIView.as_view(), name='reviews'),
]

authentication/urls.py
"""
URL configuration for the 'authentication' app.

This file defines the URL patterns for the 'authentication' app, mapping URLs to corresponding views.
"""

from django.urls import path

from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('edit-profile/', views.CreateOrEditProfileView.as_view(), name='edit-profile'),
    path('profile/<str:pk>', views.UserProfileView.as_view(), name='user-profile'),
    path('', views.ProfilesView.as_view(), name='profiles'),

    path('add-skill/', views.CreateSkillView.as_view(), name='add-skill'),
]

core/urls.py
""" URL configuration for the 'core' app."""

from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('add-project/', views.AddOrEditProjectView.as_view(), name='add-project'),
    path('edit-project/<str:pk>/', views.AddOrEditProjectView.as_view(), name='edit-project'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('project<str:pk>', views.SingleProjectView.as_view(), name='project'),
    path('project/<str:pk>/delete', views.DeleteProjectView.as_view(), name='delete-project'),

    path('add-review/<str:pk>', views.AddReview.as_view(), name='add-review')
]

authentication/models.py
""" This module contains models for the authentication app. """

from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel
from sortedm2m.fields import SortedManyToManyField


class Profile(TimeStampedModel):
    """ Model representing a user profile """

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        help_text='The related user.'
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        blank=True,
        null=True,
        help_text='Combination of id and name as a lookup field.'
    )
    skills = SortedManyToManyField(
        'Skill',
        blank=True,
        related_name='profile',
        help_text='The skills associated with the profile.'
    )
    short_intro = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text='A short intro or a post title.'
    )
    bio = models.TextField(
        blank=True,
        null=True,
        help_text='A detailed bio of the user about themselves.'
    )
    profile_picture = models.ImageField(
        upload_to='profiles/',
        default='profiles/user-default.png',
        blank=True,
        null=True,
        help_text='A profile picture of the user.'
    )
    github = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The GitHub profile link.'
    )
    linkedin = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The LinkedIn profile link.'
    )
    youtube = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The YouTube profile link.'
    )

    GenderChoices = models.TextChoices('Gender', 'Male, Female')
    gender = models.CharField(
        max_length=20,
        blank=True,
        choices=GenderChoices.choices,
        help_text='The gender of the user.'
    )

    date_of_birth = models.DateField(
        blank=True,
        null=True,
        help_text='The date of birth of the user.'
    )

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        ordering = ['created']


class Skill(TimeStampedModel):
    """ Model representing a skill """

    name = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        unique=True,
        help_text='The name of the skill.'
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        blank=True,
        null=True,
        help_text='Combination of id and name as a lookup field.'
    )
    description = models.TextField(
        blank=True,
        null=True,
        help_text='A description of the skill.'
    )

    def __str__(self):
        return self.name

authentication/forms.py
""" This module contains Django forms for handling Profile and Skill creation """

from django import forms
from sortedm2m.forms import SortedCheckboxSelectMultiple

from authentication.models import Profile, Skill


class ProfileForm(forms.ModelForm):
    """ A form for creating and updating user profiles """

    skills = SortedCheckboxSelectMultiple()

    class Meta:
        model = Profile
        exclude = ['user']

        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        """ Giving class name form-control to all the form fields so that bootstrap can be applied """

        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class SkillForm(forms.ModelForm):
    """ A form for creating and updating skills """

    class Meta:
        model = Skill
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

authentication/views.py
""" This file contains view classes for the authentication app """


from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect, render, reverse
from django.views import View
from django.views.generic import DetailView, ListView

from core.models import Project

from authentication.forms import ProfileForm, SkillForm
from authentication.models import Profile
from authentication.utils import calculate_age


class RegisterView(View):
    """
    View class for user registration.

    This view handles both the GET and POST requests for user registration """

    def get(self, request):
        """ Handle the GET request for user registration. """

        if request.user.is_authenticated:
            messages.warning(request, 'Already signed in.')
            return redirect(reverse('authentication:profiles'))

        page = 'Register'
        return render(request, 'authentication/register.html', {'page': page})

    def post(self, request):
        """ Handle the POST request for user registration. """

        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()

        else:
            messages.warning(request, 'Username already exists. Sign in instead.')
            return render(request, 'authentication/sign_in.html')
        
        login(request, user)
        return redirect(reverse('authentication:edit-profile'))


class LoginView(View):
    """
    View class for user login.

    This view handles both the GET and POST requests for user login.
    """

    def get(self, request):
        """ Handle the GET request for user login. """

        if request.user.is_authenticated:
            messages.warning(request, 'Already signed in.')
            return redirect(reverse('authentication:profiles'))

        page = 'Login'
        return render(request, 'authentication/sign_in.html', {'page': page})

    def post(self, request):
        """ Handle the POST request for user login. """

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Logged in successfully!')
            return redirect(reverse('authentication:profiles'), {'user': user})

        else:
            messages.error(request, 'Wrong Credentials.')
            return render(request, 'authentication/sign_in.html')


class CreateOrEditProfileView(LoginRequiredMixin, View):
    """ View Class for creating a profile against a User instance """

    def get(self, request):
        """ Handles the GET request for profile creation. """

        page = 'Create Profile'
        user = request.user
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            profile = None

        form = ProfileForm(instance=profile)
        context = {
            'page': page,
            'form': form,
            'profile': profile,
        }
        return render(request, 'authentication/edit-profile.html', context)

    def post(self, request):
        """
        Handles the POST request for profile creation.

        Receives the form submission and process the data to store it in the database as a profile instance.
        """
        user = request.user
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            profile = None

        form = ProfileForm(request.POST, request.FILES, instance=profile)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = user
            skills_ids = request.POST.getlist('skills')
            profile.skills.set(skills_ids)
            profile.save()
            messages.success(request, 'Success!')
            return redirect(reverse('authentication:user-profile', kwargs={'pk': profile.id}))

        else:
            messages.error(request, 'An error occurred try again!')
            return render(request, 'authentication:edit-profile.html')


class CreateSkillView(LoginRequiredMixin, View):
    """ View class for creating a skill """

    def get(self, request):
        """ Handles the get request for the form """

        page = 'Add Skill'
        form = SkillForm()
        context = {
            'page': page,
            'form': form,
        }
        return render(request, 'authentication/skill-form.html', context)

    def post(self, request):
        """
        Handles the post request.

        Receives the data from the form and creates an instance of skill in the database.
        """

        form = SkillForm(request.POST)
        form.save()
        messages.success(request, 'Skill added successfully!')
        return redirect(reverse('authentication:profiles'))


class ProfilesView(ListView):
    """
    A view that displays all the profiles """

    page = 'Profiles'
    model = Profile
    template_name = 'authentication/profiles.html'
    context_object_name = 'profiles'


class UserProfileView(DetailView):
    """ A view that displays a specific profile"""

    model = Profile
    template_name = 'authentication/single-profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        context['page'] = profile.user.get_full_name()
        context['profile'] = profile
        context['projects'] = Project.objects.filter(user=profile.user)
        context['skills'] = profile.skills.all()
        context['age'] = calculate_age(profile.date_of_birth)
        return context


class LogoutView(LogoutView):
    """ View that handles the logout functionality """

    pass

authentication/templates/authentication/edit-profile.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_tags %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Edit Profile</div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-3">
              <label for="{{ form.title.id_for_label }}" class="form-label">{{field.label}}</label>
              {{ field }}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/authentication/profiles.html
{% extends 'base.html' %}

{% load static %}

{% block specific_css %}
<link rel="stylesheet" href="{% static 'authentication/css/profiles.css' %}">
{% endblock %}

{% block content %}
<section class="main-content">
  <div class="container">
    <h1 class="text-center">Our <b>Developers</b></h1>
    <p class="text-center text-muted">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rem tenetur harum nobis
      esse ex alias.</p>
    <br><br>
    <div class="row">
      {% for profile in profiles %}
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <div class="profile-card bg-white shadow mb-4 text-center rounded-lg p-4 position-relative h-100">
          <a href="{% url 'authentication:user-profile' profile.id %}" style="text-decoration: none; color: black;">
            <div class="profile-card_image">
              <img src="{{ profile.profile_picture.url }}" alt="User" class="mb-4 shadow">
            </div>
            <div class="profile-card_details">
              <h3 class="mb-0">{{ profile.user.first_name }} {{ profile.user.last_name }}</h3>
              <p class="text-muted">{{ profile.short_intro }}</p>
              <p class="text-muted">{{ profile.bio|slice:"160" }}</p>
            </div>
            <div class="profile-card_skills row mx-auto">
              {% if profile.skills.all %}
              {% for skill in profile.skills.all%}
              <div class="col-3 mb-2">
                <span class="badge custom-badge">{{skill}}</span>
              </div>
              {% endfor %}
              {% endif %}
            </div>
            <div class="profile-card_social text-center p-4">
              {% if profile.github is not None %}
              <a href="https://github.com/{{profile.github}}" class="d-inline-block">
                <i class="fab fa-github"></i>
              </a>
              {% endif %}
              {% if profile.linkedin is not None %}
              <a href="https://www.linkedin.com/in/{{profile.linkedin}}" class="d-inline-block">
                <i class="fab fa-linkedin-in"></i>
              </a>
              {% endif %}
              {% if profile.youtube is not None %}
              <a href="https://www.youtube.com/{{profile.youtube}}" class="d-inline-block">
                <i class="fab fa-youtube"></i>
              </a>
              {% endif %}
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="h-100">
  <div class="container h-100">
    <div class="row justify-content-sm-center h-100">
      <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
        <div class="card shadow-lg">
          <div class="card-body p-5">
            <h1 class="fs-4 card-title fw-bold mb-4">Register</h1>
            <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate="" autocomplete="off">
              {% csrf_token %}
              <div class="mb-3">
                <label class="mb-2 text-muted" for="name">First Name</label>
                <input id="first-name" type="text" class="form-control" name="first_name" value="" required autofocus
                  placeholder="John">
                <div class="invalid-feedback">
                  First Name is required
                </div>
              </div>

              <div class="mb-3">
                <label class="mb-2 text-muted" for="last-name">Last Name</label>
                <input id="last-name" type="text" class="form-control" name="last_name" value="" required autofocus
                  placeholder="Doe">
                <div class="invalid-feedback">
                  Last Name is required
                </div>
              </div>

              <div class="mb-3">
                <label class="mb-2 text-muted" for="username">Username</label>
                <input id="username" type="text" class="form-control" name="username" value="" required autofocus
                  placeholder="johndoe">
                <div class="invalid-feedback">
                  Username is invalid
                </div>
              </div>

              <div class="mb-3">
                <label class="mb-2 text-muted" for="email">E-Mail Address</label>
                <input id="email" type="email" class="form-control" name="email" value="" required
                  placeholder="johndoe@something.com">
                <div class="invalid-feedback">
                  Email is invalid
                </div>
              </div>

              <div class="mb-3">
                <label class="mb-2 text-muted" for="password">Password</label>
                <input id="password" type="password" class="form-control" name="password" required
                  placeholder="*******">
                <div class="invalid-feedback">
                  Password is required
                </div>
              </div>

              <div class="mb-3">
                <label class="mb-2 text-muted" for="confirm-password">Confirm Password</label>
                <input id="confirm-password" type="password" class="form-control" name="c_password" required
                  placeholder="*******">
                <div class="invalid-feedback">
                  Password is required
                </div>
              </div>

              <div class="form-check">
                <input type="checkbox" name="terms" id="terms-n-conditions" class="form-check-input" required>
                <label for="terms-n-conditions" class="form-check-label">By registering you agree with our terms and
                  conditions.</label>
              </div>

              <div class="align-items-center d-flex">
                <button type="submit" class="btn btn-primary ms-auto">
                  Register
                </button>
              </div>
            </form>
          </div>
          <div class="card-footer py-3 border-0">
            <div class="text-center">
              Already have an account? <a href="{% url 'authentication:login' %}" class="text-dark">Login</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

authentication/templates/authentication/sign_in.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if message is not None %}
<div class="container-top">
  <div class="row">
    <div class="col-3" />
    <div class="col-6">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="col-3"></div>
    </div>
  </div>
</div>
{% endif %}

<section class="h-100">
  <div class="container h-100">
    <div class="row justify-content-sm-center h-100">
      <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
        <div class="text-center my-5">
          <img src="{% static 'images/logo.png' %}" alt="logo" width="100">
        </div>
        <div class="card shadow-lg">
          <div class="card-body p-5">
            <h1 class="fs-4 card-title fw-bold mb-4">Login</h1>

            <form method="post" action="" class="needs-validation" novalidate="" autocomplete="off">
              {% csrf_token %}
              <div class="mb-3">
                <label class="mb-2 text-muted" for="username">Username</label>
                <input id="username" type="text" class="form-control" name="username" value="" required autofocus
                  placeholder="johndoe">
                <div class="invalid-feedback">
                  Username is invalid
                </div>
              </div>

              <div class="mb-3">
                <div class="mb-2 w-100">
                  <label class="text-muted" for="password">Password</label>
                  <a href="forgot.html" class="float-end">
                    Forgot Password?
                  </a>
                </div>
                <input id="password" type="password" class="form-control" name="password" required>
                <div class="invalid-feedback">
                  Password is required
                </div>
              </div>

              <button type="submit" class="btn btn-primary ms-auto">
                Login
              </button>
          </div>
          </form>
        </div>
        <div class="card-footer py-3 border-0">
          <div class="text-center">
            Don't have an account? <a href="{% url 'authentication:register' %}" class="text-dark">Create One</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>

{% endblock %}

authentication/templates/authentication/single-profile.html
{% extends 'base.html' %}

{% load static %}

{% block specific_css %}
<link rel="stylesheet" href="{% static 'authentication/css/single-profile.css' %}">
{% endblock %}

{% block content %}

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 mb-4 mb-sm-5">
        <div class="card card-style1 border-0">
          <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
            <div class="row align-items-center">
              <div class="col-lg-6 mb-4 mb-lg-0">
                <img src="{{profile.profile_picture.url}}" width="500" alt="...">
              </div>
              <div class="col-lg-6 px-xl-10">
                <div class="bg-secondary d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
                  <h3 class="h2 text-white mb-0">{{profile.user.get_full_name}}</h3>
                  <span class="text-primary">{{profile.short_intro}}</span>
                </div>
                <ul class="list-unstyled mb-1-9">
                  <li class="mb-2 mb-xl-3 display-28"><span
                      class="display-26 text-secondary me-2 font-weight-600">Gender:</span> {{profile.gender}}
                  </li>
                  <li class="mb-2 mb-xl-3 display-28"><span
                      class="display-26 text-secondary me-2 font-weight-600">Age:</span> {{age}}
                  </li>
                  <li class="mb-2 mb-xl-3 display-28"><span
                      class="display-26 text-secondary me-2 font-weight-600">Email:</span> {{profile.user.email}}
                  </li>
                  {% if profile.linkedin is not None %}
                  <a href="https://www.linkedin.com/in/{{profile.linkedin}}"
                    style="text-decoration: none; color: black;">
                    <li class="mb-2 mb-xl-3 display-28"><span
                        class="display-26 text-secondary me-2 font-weight-600">LinkedIn:</span>
                      https://www.linkedin.com/in/{{profile.linkedin}} <i class="fab fa-linkedin-in"></i>
                    </li>
                  </a>
                  {% endif %}
                  {% if profile.github is not None %}
                  <a href="https://github.com/{{profile.github}}" style="text-decoration: none; color: black;">
                    <li class="mb-2 mb-xl-3 display-28"><span
                        class="display-26 text-secondary me-2 font-weight-600">Github:</span>
                      https://github.com/{{profile.github}} <i class="fab fa-github"></i>
                    </li>
                  </a>
                  {% endif %}
                  {% if profile.youtube is not None %}
                  <a href="https://www.youtube.com/{{profile.youtube}}" style="text-decoration: none; color: black;">
                    <li class="display-28"><span class="display-26 text-secondary me-2 font-weight-600">Youtube:</span>
                      https://www.youtube.com/{{profile.youtube}} <i class="fab fa-youtube"></i>
                    </li>
                  </a>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12 mb-4 mb-sm-5">
        <div>
          <span class="section-title text-primary mb-3 mb-sm-4">About Me</span>
          <p>{{profile.bio}}</p>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-12 mb-4 mb-sm-5">
            <div class="mb-4 mb-sm-5">
              <span class="section-title text-primary mb-3 mb-sm-4">Skills</span>
              <div class="progress-text">
                {% for skill in skills %}
                <div class="row">
                  <div class="col-6">{{skill.name}}</div>
                </div>
                {% endfor %}
                <div>
                  <hr>
                  <span class="section-title text-primary mb-3 mb-sm-4">Projects</span>

                  {% include '_projects_template.html' %}

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-auto">
            <a href="{% url 'authentication:edit-profile' %}">
              <button class="btn btn-primary">Edit Profile</button>
            </a>
          </div>
          <div class="col-auto">
            <a href="{% url 'core:add-project' %}">
              <button class="btn btn-warning">Add Project</button>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

authentication/templates/authentication/skill-form.html
{% extends 'base.html' %}

{% load bootstrap_tags %}

{% block content %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Add Skill</div>
        <div class="card-body">
          <form method="post" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{ form.title.id_for_label }}" class="form-label">{{field.label}}</label>
              {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}