Code-Book/urls.py
"""
URL configuration for the project.

This file defines the URL patterns for the project, mapping URLs to corresponding views.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),

    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
""" URL configuration for the 'api' app """

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'profiles', views.ProfileViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'auth', views.AuthViewSet, basename='auth')

urlpatterns = [
    path('', include(router.urls)),
    path('reviews/', views.ReviewAPIView.as_view(), name='reviews'),
]

authentication/urls.py
"""
URL configuration for the 'authentication' app.

This file defines the URL patterns for the 'authentication' app, mapping URLs to corresponding views.
"""

from django.urls import path

from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('edit-profile/', views.CreateOrEditProfileView.as_view(), name='edit-profile'),
    path('profile/<str:pk>', views.UserProfileView.as_view(), name='user-profile'),
    path('', views.ProfilesView.as_view(), name='profiles'),

    path('add-skill/', views.CreateSkillView.as_view(), name='add-skill'),
]

core/urls.py
""" URL configuration for the 'core' app."""

from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('add-project/', views.AddOrEditProjectView.as_view(), name='add-project'),
    path('edit-project/<str:pk>/', views.AddOrEditProjectView.as_view(), name='edit-project'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('project<str:pk>', views.SingleProjectView.as_view(), name='project'),
    path('project/<str:pk>/delete', views.DeleteProjectView.as_view(), name='delete-project'),

    path('add-review/<str:pk>', views.AddReview.as_view(), name='add-review')
]

core/models.py
""" This module contains models for the core app. """

from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel
from sortedm2m.fields import SortedManyToManyField

from authentication.models import Skill


class Project(TimeStampedModel):
    """ A model representing a project """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        related_name='project',
        help_text='The user that created the project.'
    )
    title = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The title of the project.'
    )
    slug = models.SlugField(
        blank=True,
        null=True,
        max_length=50,
        unique=True,
        help_text='Combination of id and title as a lookup field.'
    )
    description = models.TextField(
        blank=True,
        null=True,
        help_text='The detailed description of the project.'
    )
    featured_image = models.ImageField(
        upload_to='projects/',
        default='projects/default.jpg',
        blank=True,
        null=True,
        help_text='The featured image of the project.'
    )
    youtube_link = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The link to the YouTube video of the project.'
    )
    demo_link = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The link to the demo of the project(if deployed).'
    )
    source_code_link = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text='The link to the source code of the project.'
    )
    skills = SortedManyToManyField(
        Skill,
        blank=True,
        related_name='Project',
        help_text='The relevant skills in the project.'
    )

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.title


class Review(TimeStampedModel):
    """ A model representing a review for a project """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='review',
        help_text='The user who wrote the review.'
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='review',
        help_text='The project that is being reviewed.'
    )
    VoteChoices = models.TextChoices('Vote', 'Up, Down')
    vote = models.CharField(
        max_length=20,
        blank=True,
        choices=VoteChoices.choices,
        help_text='The vote choice (Up or Down).'
    )
    body = models.TextField(
        blank=True,
        null=True,
        help_text='The content of the review.'
    )

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.vote

core/forms.py
""" A form for creating and updating project instances """

from django import forms
from django.forms import ModelForm
from sortedm2m.forms import SortedCheckboxSelectMultiple

from core.models import Project, Review


class ProjectForm(ModelForm):
    """ A form for creating and updating project instances """

    skills = SortedCheckboxSelectMultiple()

    class Meta:
        model = Project
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ReviewForm(ModelForm):
    """ A form for creating and updating review instances for projects """

    class Meta:
        model = Review
        fields = ['body', 'vote']

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-input'}),
        }

core/views.py
""" This module contains Django views for handling project-related actions """

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from core.forms import ProjectForm, ReviewForm
from core.models import Project, Review


class AddOrEditProjectView(LoginRequiredMixin, View):
    """ A view to handle adding new projects by authenticated users """

    def get(self, request, pk=None):
        """ Handle HTTP GET request for adding a new project or editing ann existing one """

        page = 'Add Project'

        if pk:
            project = get_object_or_404(Project, pk=pk, user=request.user)
            form = ProjectForm(instance=project)
        else:
            form = ProjectForm()
            
        context = {
            'page': page,
            'form': form,
        }
        return render(request, 'core/project_form.html', context)

    def post(self, request, pk=None):
        """ Handle HTTP POST request for adding a new project or editing an existing one"""

        user = request.user

        if pk:
            project = get_object_or_404(Project, pk=pk, user=user)
            form = ProjectForm(request.POST, request.FILES, instance=project)
        else:
            form = ProjectForm(request.POST)

        if form.is_valid():
            project = form.save(commit=False)
            project.user = user
            project.save()
            tags_ids = request.POST.getlist('skills')
            project.skills.set(tags_ids)
            messages.success(request, 'Project added/edited!')
            return redirect(reverse('core:project', kwargs={'pk': project.id}))

        else:
            messages.error(request, 'An error occurred!')
            return render(request, 'core/project_form.html')


class DeleteProjectView(LoginRequiredMixin, DeleteView):
    """ A view to handle the deletion of a project instance """

    model = Project
    success_url = reverse_lazy('core:projects')

    
class AddReview(LoginRequiredMixin, CreateView):
    """ A view to handle the addition of new reviews by authenticated users """

    model = Review
    form_class = ReviewForm
    template_name = 'core/single_project.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        project_id = self.kwargs.get('pk')

        if project_id:
            try:
                project = Project.objects.get(id=project_id)
                form.instance.project = project
            except Project.DoesNotExist:
                pass
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('core:project', args=[self.kwargs['pk']])


class ProjectsView(ListView):
    """ A view to display list of projects """

    page = 'Projects'
    model = Project
    template_name = 'core/projects.html'
    context_object_name = 'projects'


class SingleProjectView(DetailView):
    """ A view to display a specific project """

    model = Project
    template_name = 'core/single_project.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        project = self.get_object()
        context['project'] = project
        context['page'] = project.title
        context['tags'] = project.skills.all()
        context['reviews'] = project.review_set.all()
        context['user_reviewed'] = Review.objects.filter(project=project, user_id=self.request.user.pk).exists()
        up_votes = Review.objects.filter(project=project, vote='Up').count()
        try:
            ratio = (up_votes * 100) // Review.objects.filter(project=project).count()
        except ZeroDivisionError:
            ratio = 0

        context['votes_ratio'] = ratio
        context['form'] = ReviewForm()
        return context

core/templates/core/project_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">Delete Project</h1>
  <form method="post" class="mb-4">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" class="btn btn-danger">Confirm</button>
    <a href="{% url 'core:projects' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock %}

core/templates/core/project_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Add Project</div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-3">
              <label for="{{ form.title.id_for_label }}" class="form-label">{{field.label}}</label>
              {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

core/templates/core/projects.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include '_projects_template.html' %}

{% endblock %}

core/templates/core/single_project.html
{% extends 'base.html' %}

{% load static %}

{% block specific_css %}
<link rel="stylesheet" href="{% static 'core/css/single-project.css' %}">
{% endblock %}

{% block content %}


<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="m-auto d-flex justify-content-center">
        <h1 class="project-title mt-4 mb-3">{{project.title}}</h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-5">
      <div class="project-info-box mt-0">
        <h5>PROJECT DETAILS</h5>
        <p class="mb-0 text-muted">{{project.description}}</p>
      </div>

      <div class="project-info-box">
        <dl class="row">
          <dt class="col-sm-3">Author</dt>
          <dd class="col-sm-9 text-muted">
            <a href="{% url 'authentication:user-profile' project.user.id %}">{{project.user.get_full_name}}</a>
          </dd>
          {% if project.source_code_link is not None %}
          <dt class="col-sm-3">Source</dt>
          <dd class="col-sm-9">
            <a class="text-muted" href="{{project.source_code_link}}">{{project.source_code_link}}</a>
          </dd>
          {% endif %}
          {% if project.demo_link is not None %}
          <dt class="col-sm-3">Demo</dt>
          <dd class="col-sm-9">
            <a class="text-muted" href="{{project.demo_link}}">{{project.demo_link}}</a>
          </dd>
          {% endif %}
      </div>


    </div>

    <div class="col-md-7">
      <img src="{{project.featured_image.url}}" alt="project-image" class="rounded" width="700">
      <div class="project-info-box">
        <div class="col-12 mb-2 inline">
          {% for tag in tags %}
          <span class="badge custom-badge">{{tag}}</span>
          {% endfor %}
        </div>
      </div>
      {% if project.youtube_link is not None %}
      <div class="project-info-box mt-0 mb-0 d-flex justify-content-center">
        <div>
          <i class="fab fa-youtube"></i>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<div class="container">
  <div class="be-comment-block">
    <h6 class="comments-title">Votes Ratio {{votes_ratio}}%</h6>
    <h1 class="comments-title">Review{{ reviews.count|pluralize }} ({{ reviews.count }})</h1>
    {% for review in reviews %}
    <div class="be-comment">
      <div class="be-img-comment">
        <a href="{% url 'authentication:user-profile' review.user.id %}">
          <img src="{{review.user.profile.profile_picture.url}}" alt="" class="be-ava-comment">
        </a>
      </div>
      <div class="be-comment-content">

        <span class="be-comment-name">
          <a href="{% url 'authentication:user-profile' review.user.id %}">
            {{review.user.get_full_name}}
            {% if review.vote == 'Up' %}
            <i class="fas fa-thumbs-up"></i>
            {% else %}
            <i class="fas fa-thumbs-down"></i>
            {% endif %}
          </a>
        </span>
        <span class="be-comment-time">
          <i class="fa fa-clock-o"></i>
          {{review.created}}
        </span>

        <p class="be-comment-text">
          {{review.body}}
        </p>
      </div>
    </div>
    {% endfor %}

    {% if request.user == project.user %}

    {% elif user_reviewed %}
    <p>You have already submitted your review for this project</p>

    {% elif request.user.is_authenticated %}
    <form class="form-block" method="post" action="{% url 'core:add-review' project.id %}">
      {% csrf_token %}
      {{form.vote}}
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            {{form.body}}
          </div>
        </div>
        <a class="d-flex justify-content-end">
          <button class="btn btn-primary">Add review</button>
        </a>
      </div>
    </form>
    {% else %}
    <a href="{% url 'authentication:login' %}?next={{request.path}}">Please login to leave a review</a>
    {% endif %}
  </div>
</div>

{% if request.user == project.user %}
<div class="container">
  <div class="row">
    <div class="col-11 d-flex justify-content-end">
      <a href="{% url 'core:delete-project' project.id %}">
        <button class="btn btn-danger">Delete</button>
      </a>
    </div>
    <div class="col-1 d-flex justify-content-end">
      <a href="{% url 'core:edit-project' project.id %}">
        <button class="btn btn-warning">Edit</button>
      </a>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}