Code-Book/urls.py
"""
URL configuration for the project.

This file defines the URL patterns for the project, mapping URLs to corresponding views.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),

    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
""" URL configuration for the 'api' app """

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'profiles', views.ProfileViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'auth', views.AuthViewSet, basename='auth')

urlpatterns = [
    path('', include(router.urls)),
    path('reviews/', views.ReviewAPIView.as_view(), name='reviews'),
]

authentication/urls.py
"""
URL configuration for the 'authentication' app.

This file defines the URL patterns for the 'authentication' app, mapping URLs to corresponding views.
"""

from django.urls import path

from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('edit-profile/', views.CreateOrEditProfileView.as_view(), name='edit-profile'),
    path('profile/<str:pk>', views.UserProfileView.as_view(), name='user-profile'),
    path('', views.ProfilesView.as_view(), name='profiles'),

    path('add-skill/', views.CreateSkillView.as_view(), name='add-skill'),
]

core/urls.py
""" URL configuration for the 'core' app."""

from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('add-project/', views.AddOrEditProjectView.as_view(), name='add-project'),
    path('edit-project/<str:pk>/', views.AddOrEditProjectView.as_view(), name='edit-project'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('project<str:pk>', views.SingleProjectView.as_view(), name='project'),
    path('project/<str:pk>/delete', views.DeleteProjectView.as_view(), name='delete-project'),

    path('add-review/<str:pk>', views.AddReview.as_view(), name='add-review')
]

templates/_projects_template.html
{% load static %}

{% block specific_css %}
<link rel="stylesheet" href="{% static 'core/css/projects.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    {% for project in projects %}
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <a href="{% url 'core:project' project.id %}" style="text-decoration: none; color: black;">
        <div class="card shadow">
          <img src="{{project.featured_image.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title">{{project.title}}</h2>
            <a href="#"
              style="text-decoration: none; color: cornflowerblue; font-style: italic;">
              <h6 class="text-muted font-italic">By {{project.user.first_name}} {{project.user.last_name}}</h6>
            </a>
          </div>
          <div class="card_skills row mx-auto mb-3">
            {% if project.skills.all %}
            {% for tag in project.skills.all %}
            <div class="col-3 mb-2">
              <span class="badge custom-badge">{{tag}}</span>
            </div>
            {% endfor %}
            {% endif %}
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block specific_css %} {% endblock %} <title>Code Book |{{ page }}</title>
</head>

<nav class="navbar navbar-expand-lg navbar-light ftco_navbar bg-white ftco-navbar-light" id="ftco-navbar">
  <div class="container" id="nav-container">
    <a class="navbar-brand" href="{% url 'authentication:profiles' %}">Code Book</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#ftco-nav" aria-controls="ftco-nav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="ftco-nav">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="{% url 'core:projects' %}" class="nav-link">Projects</a></li>
        <li class="nav-item"><a href="{% url 'authentication:profiles' %}" class="nav-link">Developers</a></li>
        {% if request.user.is_authenticated%}
        <li>
          <div class="btn-group">
            {% if user.profile %}
            <a href="{% url 'authentication:user-profile' user.profile.id %}">
              <button type="button" class="btn btn-warning">{{user.get_full_name}}</button>
            </a>
            {% endif %}
            <button type="button" class="btn btn-warning dropdown-toggle dropdown-toggle-split"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'authentication:edit-profile' %}">Edit Profile</a>
              {% if user.profile %}
              <a class="dropdown-item" href="{% url 'authentication:user-profile' user.profile.id %}">View Profile</a>
              <a class="dropdown-item" href="{% url 'core:add-project' %}">Add a project</a>
              <a class="dropdown-item" href="{% url 'authentication:add-skill' %}">Add a skill</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
            </div>
          </div>
        </li>
        {% else %}
        <li class="nav-item"><a href="{% url 'authentication:login' %}" class="nav-link">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


<body>
  {% if messages %}
  {% for message in messages %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        {% if message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {% else %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {% endif %}
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}

    <main>
      {% block content %}

      {% endblock %}
    </main>
</body>
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">&copy; 2023 Code Book, Inc</p>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'authentication:profiles' %}" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="{% url 'core:projects' %}" class="nav-link px-2 text-muted">Projects</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
  </footer>
</div>

</html>